version: 2

sources:
  - name: bank_marketing_dwh
    database: datafellowship9
    tables:
      - name: fact_bank_marketing
      - name: dim_credit
      - name: dim_job
      - name: dim_education
      - name: dim_marital